### ISSUE TITLE
Issue with loading the galah catalogue using a script located outside the gaia_tools directory

### ISSUE THREAD

**Issue by vighneshnagpal** [jobovy/gaia_tools#27]
Dear Dr. Bovy,
I would like to report a bug I found while trying to use the code to load data from the Galah catalogue.

```
import gaia_tools.load as gload
galah_cat = gload.galah()

```
Running a script with the above code in a directory other than the gaia_tools directory results in the following error: 

```
--2020-06-24 21:43:25--  https://datacentral.aao.gov.au/teamdata/GALAH/public/GALAH_DR2.1_catalog.fits
Resolving datacentral.aao.gov.au (datacentral.aao.gov.au)... 203.15.109.202
Connecting to datacentral.aao.gov.au (datacentral.aao.gov.au)|203.15.109.202|:443... connected.
ERROR: cannot verify datacentral.aao.gov.au's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to datacentral.aao.gov.au insecurely, use
``` `--no-check-certificate'.
--2020-06-24 21:43:26--  https://datacentral.aao.gov.au/teamdata/GALAH/public/GALAH_DR2.1_catalog.fits
Resolving datacentral.aao.gov.au (datacentral.aao.gov.au)... 203.15.109.202
Connecting to datacentral.aao.gov.au (datacentral.aao.gov.au)|203.15.109.202|:443... connected.
ERROR: cannot verify datacentral.aao.gov.au's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to datacentral.aao.gov.au insecurely, use `--no-check-certificate'.
--2020-06-24 21:43:27--  https://datacentral.aao.gov.au/teamdata/GALAH/public/GALAH_DR2.1_catalog.fits
Resolving datacentral.aao.gov.au (datacentral.aao.gov.au)... 203.15.109.202
Connecting to datacentral.aao.gov.au (datacentral.aao.gov.au)|203.15.109.202|:443... connected.
ERROR: cannot verify datacentral.aao.gov.au's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to datacentral.aao.gov.au insecurely, use `--no-check-certificate'.
Traceback (most recent call last):
  File "/home/vnagpal/miniconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/load/download.py", line 225, in _download_file
    subprocess.check_call(cmd)
  File "/home/vnagpal/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://datacentral.aao.gov.au/teamdata/GALAH/public/GALAH_DR2.1_catalog.fits', '-O', '/tmp/tmpv_10hk3s', '--read-timeout=10', '--tries=3']' returned non-zero exit status 5.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "read.py", line 2, in <module>
    galah_cat = gload.galah()
  File "/home/vnagpal/miniconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/load/__init__.py", line 315, in galah
    download.galah(dr=dr)
  File "/home/vnagpal/miniconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/load/download.py", line 100, in galah
    filePath,verbose=verbose,spider=spider)
  File "/home/vnagpal/miniconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/load/download.py", line 234, in _download_file
    raise IOError('File %s does not appear to exist on the server ...' % (os.path.basename(filePath)))

'

 
However, this error does not occur when the same two lines of code are run from within the gaia_tools directory.

Thanks!

**Comment by jobovy** [comment]
I'm surprised that this would work if run in the ``gaia_tools`` directory, since this seems to be an issue with the server that the GALAH data is served from. If I just try going to https://datacentral.aao.gov.au/teamdata/GALAH/public/GALAH_DR2.1_catalog.fits I get
```
Error during SSL Handshake with remote server
```
so I think there is something wrong with the SSL certificate of their server. I would contact the GALAH team about this and make sure that things are working on their end. If they give you a new URL, please link it here so I can update the code.

If they don't respond and you need the GALAH data urgently, send me an email and I can send you a copy.

**Comment by vighneshnagpal** [comment]
Thanks for the quick response, Dr Bovy. I'll try emailing them and update you with the link if they provide me with one.
