### ISSUE TITLE
Issue with gaia_tools.select.tgasSelect()

### ISSUE THREAD

**Issue by jgjiang01** [jobovy/gaia_tools#28]
Hi!
I'm learning how to use gaia_tools. When I run the the following two commands,
```
>>> import gaia_tools.select
>>> tsf= gaia_tools.select.tgasSelect()
```
I get the error message:
```
Traceback (most recent call last):
  File "/home/ubantu/.local/lib/python3.6/site-packages/numpy/lib/histograms.py", line 1051, in histogramdd
    n = operator.index(bins[i])
TypeError: 'numpy.float64' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gaia_tools-0.2-py3.6.egg/gaia_tools/select/tgasSelect.py", line 124, in __init__
    self._determine_selection(jmin,jmax,jkmin,jkmax)
  File "/usr/local/lib/python3.6/dist-packages/gaia_tools-0.2-py3.6.egg/gaia_tools/select/tgasSelect.py", line 171, in _determine_selection
    [jkmin,jkmax],[-0.5,_BASE_NPIX-0.5]],weights=_2mc[3])
  File "<__array_function__ internals>", line 6, in histogramdd
  File "/home/ubantu/.local/lib/python3.6/site-packages/numpy/lib/histograms.py", line 1056, in histogramdd
    ) from e
TypeError: `bins[0]` must be an integer, when a scalar
```
but I don't know how to fix it? My system is Ubantu 18.04, and the python version is 3.6.9.
Any insight will be appreciated!

**Comment by jobovy** [comment]
I think this is because the bins argument for the version of ``numpy`` that you are using must be an integer (before, a float was allowed). I checked in a fix, please try whether that fixes your issue!
